[package]
name = "gui"
version = "0.1.0"
authors = ["antlilja <liljaanton2001@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chackad = { path = "../chackad" }
piston_window = "*"
